sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_script:
  - wget -q https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
